---
galaxy_info:
  role_name: vulns_disable_firewall
  namespace: dreadnode
  author: Dreadnode
  description: vulns disaule firewall
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all

dependencies: []
