---
dependency:
  name: galaxy
  options:
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/../../requirements.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/../../requirements.yml

driver:
  name: default

platforms:
  - name: localhost
    managed: false

provisioner:
  name: ansible
  config_file: ${MOLECULE_PROJECT_DIRECTORY}/../../ansible.cfg
  playbooks:
    converge: converge.yml

scenario:
  test_sequence:
    - dependency
    - syntax

verifier:
  name: ansible
