---
- name: Force a DNS on the adapter {{ nat_adapter }}
  ansible.windows.win_dns_client:
    adapter_names: "{{ nat_adapter }}"
    dns_servers: 
      - "{{ dns_server }}"
      - "{{ dns_server_forwarder }}"
  when: force_dns_server | bool

- name: Set a proxy for specific protocols
  ansible.windows.win_inet_proxy:
    proxy:
      http: "{{ ad_http_proxy }}"
      https: "{{ ad_https_proxy }}"
    bypass: ["<local>", "*.local", "169.254.169.254"]
  when: enable_http_proxy | bool

- name: Configure IE to use a specific proxy per protocol
  ansible.windows.win_inet_proxy:
    proxy:
      http: "{{ ad_http_proxy }}"
      https: "{{ ad_https_proxy }}"
    bypass: ["<local>", "*.local", "169.254.169.254"]
  when: enable_http_proxy | bool

- name: Upgrade module PowerShellGet to fix accept license issue
  ansible.windows.win_shell: |
    $ProgressPreference = 'SilentlyContinue'
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Install-PackageProvider -Name NuGet -Force
    Install-Module PowerShellGet -Force

- name: Check if ComputerManagementDsc exists
  ansible.windows.win_shell: |
    if (Get-Module -ListAvailable -Name ComputerManagementDsc) {
      exit 0
    } else {
      exit 1
    }
  register: module_check
  failed_when: false
  changed_when: false

- name: Install ComputerManagementDsc only if needed
  community.windows.win_psmodule:
    name: ComputerManagementDsc
    state: present
  when: module_check.rc != 0

- name: Check if ActiveDirectoryDSC exists
  ansible.windows.win_shell: |
    if (Get-Module -ListAvailable -Name ActiveDirectoryDSC) {
      exit 0
    } else {
      exit 1
    }
  register: ad_dsc_check
  failed_when: false
  changed_when: false

- name: Install ActiveDirectoryDSC only if needed
  community.windows.win_psmodule:
    name: ActiveDirectoryDSC
    state: present
  register: ad_dsc_module
  when: ad_dsc_check.rc != 0

- name: Windows | Enable Remote Desktop
  ansible.windows.win_dsc:
    resource_name: RemoteDesktopAdmin
    IsSingleInstance: 'Yes'
    Ensure: present
    UserAuthentication: Secure

- name: Check if xNetworking exists
  ansible.windows.win_shell: |
    if (Get-Module -ListAvailable -Name xNetworking) {
      exit 0
    } else {
      exit 1
    }
  register: xnetworking_check
  failed_when: false
  changed_when: false

- name: Install xNetworking only if needed
  community.windows.win_psmodule:
    name: xNetworking
    state: present
  when: xnetworking_check.rc != 0

- name: Firewall | Allow RDP through Firewall
  ansible.windows.win_dsc:
    resource_name: xFirewall
    Name: "Administrator access for RDP (TCP-In)"
    Ensure: present
    Enabled: True
    Profile: "Domain"
    Direction: "Inbound"
    Localport: "3389"
    Protocol: "TCP"
    Description: "Opens the listener port for RDP"

- name: Add a network static route
  ansible.windows.win_route:
    destination: "{{ route_network }}"
    gateway: "{{ route_gateway }}"
    metric: 1
    state: present
  when: add_route | bool
