---
galaxy_info:
  role_name: security_audit_policy
  namespace: dreadnode
  author: Dreadnode
  description: security audit policy
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Windows
      versions:
        - all

dependencies: []
