---
- name: Configure SCOPE-RANGE databases
  hosts: data
  become: true
  gather_facts: true
  roles:
    - role: dreadnode.goad.scope_range_data

- name: Configure SCOPE-RANGE storage services
  hosts: storage
  become: true
  gather_facts: true
  roles:
    - role: dreadnode.goad.scope_range_storage
