package cmd

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/dreadnode/dreadgoad/internal/sshconfig"
	"github.com/spf13/cobra"
)

var (
	initOutPath        string
	initNonInteractive bool
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Interactive setup wizard — write a dreadgoad.yaml ready to use",
	Long: `Walks through provider selection and connectivity probing, then writes
a working dreadgoad.yaml. For Ludus the wizard prefers an ssh_config Host
alias so existing key/agent setups (including 1Password) carry through with
zero extra configuration.

This is the recommended first command for new users. Power users who want a
boilerplate file can use 'dreadgoad config init' instead.`,
	RunE: runInit,
}

func init() {
	initCmd.Flags().StringVar(&initOutPath, "out", "", "Path to write the config (default: ./dreadgoad.yaml)")
	initCmd.Flags().BoolVar(&initNonInteractive, "non-interactive", false, "Fail instead of prompting (for CI)")
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, _ []string) error {
	out := initOutPath
	if out == "" {
		cwd, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getwd: %w", err)
		}
		out = filepath.Join(cwd, "dreadgoad.yaml")
	}
	if _, err := os.Stat(out); err == nil {
		return fmt.Errorf("%s already exists — refusing to overwrite (use --out to choose a different path)", out)
	}

	if initNonInteractive {
		return fmt.Errorf("init is interactive; --non-interactive was set with no values to apply")
	}

	in := bufio.NewReader(cmd.InOrStdin())
	w := cmd.OutOrStdout()

	fmt.Fprintln(w, "DreadGOAD setup")
	fmt.Fprintln(w, strings.Repeat("=", 40))

	provider := promptChoice(in, w, "Provider?", []string{"ludus", "aws", "proxmox"}, "ludus")

	switch provider {
	case "ludus":
		return runInitLudus(cmd.Context(), in, w, out)
	case "aws":
		return runInitAWS(in, w, out)
	default:
		return fmt.Errorf("provider %q not yet supported by the wizard — use 'dreadgoad config init' for a blank file", provider)
	}
}

func runInitLudus(ctx context.Context, in *bufio.Reader, w io.Writer, out string) error {
	mode := promptChoice(in, w, "Where will DreadGOAD run?", []string{"remote", "local"}, "remote")

	cfg := struct {
		Host   string
		APIKey string
	}{}

	if mode == "remote" {
		cfg.Host = promptString(in, w, "SSH target for the Ludus server (alias from ~/.ssh/config or hostname)", "proxmox")

		// Resolve and report what ssh would do — gives the user a clear
		// signal that the alias is being picked up before we try to probe.
		if r, err := sshconfig.Resolve(cfg.Host); err == nil {
			extra := ""
			if r.User != "" && r.User != cfg.Host {
				extra = fmt.Sprintf(" as %s", r.User)
			}
			fmt.Fprintf(w, "  ssh resolves %q → %s:%d%s\n", cfg.Host, r.Hostname, r.Port, extra)
		}

		fmt.Fprintf(w, "  Probing %q over SSH (5s timeout)...\n", cfg.Host)
		if err := probeRemoteLudus(ctx, cfg.Host); err != nil {
			fmt.Fprintf(w, "  warn: %v\n", err)
			if !promptYesNo(in, w, "Continue anyway?", false) {
				return fmt.Errorf("aborted")
			}
		} else {
			fmt.Fprintln(w, "  ok: ludus reachable")
		}
	} else {
		if _, err := exec.LookPath("ludus"); err != nil {
			fmt.Fprintln(w, "  warn: ludus CLI not found in PATH — install it before running 'dreadgoad up'")
		} else {
			fmt.Fprintln(w, "  ok: ludus CLI found in PATH")
		}
	}

	cfg.APIKey = promptSecret(in, w, "Ludus API key (leave blank to set LUDUS_API_KEY env var instead)")

	return writeLudusConfig(out, cfg.Host, cfg.APIKey)
}

func probeRemoteLudus(ctx context.Context, target string) error {
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	// `ludus version --json` is the lightest call that proves the binary
	// is on PATH on the remote and the SSH credentials work.
	cmd := exec.CommandContext(ctx, "ssh", "-o", "LogLevel=ERROR", target, "ludus", "version", "--json")
	out, err := cmd.CombinedOutput()
	if err != nil {
		trimmed := strings.TrimSpace(string(out))
		if trimmed != "" {
			return fmt.Errorf("%s: %w", trimmed, err)
		}
		return err
	}
	return nil
}

func runInitAWS(in *bufio.Reader, w io.Writer, out string) error {
	region := promptString(in, w, "AWS region", "us-east-1")
	env := promptString(in, w, "Environment name", "staging")
	body := fmt.Sprintf(`# DreadGOAD configuration — generated by 'dreadgoad init'
provider: aws
env: %s
region: %s
`, env, region)
	return writeFile(out, body)
}

func writeLudusConfig(out, host, apiKey string) error {
	var b strings.Builder
	b.WriteString("# DreadGOAD configuration — generated by 'dreadgoad init'\n")
	b.WriteString("provider: ludus\n")
	b.WriteString("env: staging\n")
	b.WriteString("ludus:\n")
	if apiKey != "" {
		b.WriteString(fmt.Sprintf("  api_key: %s\n", apiKey))
	} else {
		b.WriteString("  # api_key set via LUDUS_API_KEY env var\n")
	}
	if host != "" {
		b.WriteString(fmt.Sprintf("  host: %s\n", host))
	}
	if err := writeFile(out, b.String()); err != nil {
		return err
	}
	if apiKey == "" {
		fmt.Printf("\nReminder: export LUDUS_API_KEY='...' before running 'dreadgoad up'\n")
	}
	return nil
}

func writeFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	fmt.Printf("\nWrote %s\n", path)
	fmt.Println("Next: dreadgoad doctor   # verify everything")
	fmt.Println("Then: dreadgoad up       # deploy the lab end-to-end")
	return nil
}

func promptString(in *bufio.Reader, w io.Writer, label, def string) string {
	if def != "" {
		fmt.Fprintf(w, "%s [%s]: ", label, def)
	} else {
		fmt.Fprintf(w, "%s: ", label)
	}
	line, _ := in.ReadString('\n')
	line = strings.TrimSpace(line)
	if line == "" {
		return def
	}
	return line
}

func promptSecret(in *bufio.Reader, w io.Writer, label string) string {
	// We deliberately don't suppress echo: the user is mid-setup at a
	// trusted terminal and the visible feedback ("did I paste the right
	// thing?") is more valuable than over-the-shoulder protection here.
	fmt.Fprintf(w, "%s: ", label)
	line, _ := in.ReadString('\n')
	return strings.TrimSpace(line)
}

func promptChoice(in *bufio.Reader, w io.Writer, label string, choices []string, def string) string {
	for {
		fmt.Fprintf(w, "%s [%s] (default %s): ", label, strings.Join(choices, "/"), def)
		line, _ := in.ReadString('\n')
		line = strings.TrimSpace(strings.ToLower(line))
		if line == "" {
			return def
		}
		for _, c := range choices {
			if c == line {
				return c
			}
		}
		fmt.Fprintf(w, "  %q is not one of %s\n", line, strings.Join(choices, ", "))
	}
}

func promptYesNo(in *bufio.Reader, w io.Writer, label string, def bool) bool {
	suffix := "[y/N]"
	if def {
		suffix = "[Y/n]"
	}
	fmt.Fprintf(w, "%s %s: ", label, suffix)
	line, _ := in.ReadString('\n')
	line = strings.TrimSpace(strings.ToLower(line))
	if line == "" {
		return def
	}
	return line == "y" || line == "yes"
}
