---
# Load data
- ansible.builtin.import_playbook: data.yml
  tags: data

# set AD datas ==================================================================================================
- name: Servers AD configuration
  hosts: server
  roles:
    - { role: 'member_server', tags: 'server'}
  vars:
    member_domain: "{{ lab.hosts[dict_key].domain }}"
    domain_username: "{{ admin_user }}@{{ member_domain }}"
    domain_password: "{{ lab.domains[member_domain].domain_password }}"
    domain_dc: "{{ lab.domains[member_domain].dc }}"
    dns_server_ip: "{{ hostvars[domain_dc]['dc_ipv4'] | default(hostvars[domain_dc].ansible_host) }}"
    dc_hostname_to_ip: "{{ hostvars[groups['dc'][0]]['dc_hostname_to_ip'] | default({}) }}"
    instance_to_ip: "{{ hostvars[groups['dc'][0]]['instance_to_ip'] | default({}) }}"

- name: Workstations AD configuration
  hosts: workstation
  roles:
    - { role: 'commonwkstn', tags: 'workstation'}
  vars:
    member_domain: "{{ lab.hosts[dict_key].domain }}"
    domain_username: "{{ admin_user }}@{{ member_domain }}"
    domain_password: "{{ lab.domains[member_domain].domain_password }}"
    domain_dc: "{{ lab.domains[member_domain].dc }}"
    dns_server_ip: "{{ hostvars[domain_dc]['dc_ipv4'] | default(hostvars[domain_dc].ansible_host) }}"
    dc_hostname_to_ip: "{{ hostvars[groups['dc'][0]]['dc_hostname_to_ip'] | default({}) }}"
    instance_to_ip: "{{ hostvars[groups['dc'][0]]['instance_to_ip'] | default({}) }}"
