---
# Load datas
- ansible.builtin.import_playbook: data.yml
  tags: 'data'

# set AD datas ==================================================================================================
- name: Play servers AD configuration
  hosts: server
  roles:
    - { role: 'member_server', tags: 'server'}
  vars:
    member_domain: "{{ lab.hosts[dict_key].domain }}"
    domain_username: "{{ admin_user }}@{{ member_domain }}"
    domain_password: "{{ lab.domains[member_domain].domain_password }}"

- name: Play workstations AD configuration
  hosts: workstation
  roles:
    - { role: 'commonwkstn', tags: 'workstation'}
  vars:
    member_domain: "{{ lab.hosts[dict_key].domain }}"
    domain_username: "{{ admin_user }}@{{ member_domain }}"
    domain_password: "{{ lab.domains[member_domain].domain_password }}"