---
collections:
  # Install a collection from Ansible Galaxy.
  - name: ansible.windows
    version: 3.5.0
  - name: community.general
  - name: community.windows
    version: 3.1.0
  - name: chocolatey.chocolatey
# - name: goad.windows
#   type: dir
#   source: ./collections/goad/windows
