"""Extension discovery and topology reseeding after mutating commands."""

from __future__ import annotations

import json
import os
import typing as t

from . import commands, labconfig, paths, projectroot
from .cli import Capture, capture
from .schemas import PersistedRangeDocument, RangeHost, new_range_host

_EXT_ROLE = "linux"


async def extension_nodes(
    session: t.Mapping[str, t.Any], capture_command: Capture | None = None
) -> list[RangeHost]:
    """Return nodes belonging to enabled extensions."""
    anchor = session.get("anchor", {})
    config_path, env = anchor.get("config_path"), anchor.get("env")
    if not config_path or not env:
        return []
    argv = [
        commands.resolve_bin(str(paths.repo_root())),
        "--config",
        str(config_path),
        "--env",
        str(env),
        "extension",
        "list",
        "--json",
    ]
    runner = capture_command or capture
    # `extension list` reads the config's own tree; run there, like every other
    # spawn (projectroot.run_cwd).
    return_code, stdout, _stderr = await runner(
        argv, projectroot.run_cwd(session, paths.repo_root())
    )
    if return_code != 0:
        return []
    try:
        extensions = json.loads(stdout)
    except Exception:  # noqa: BLE001
        return []
    nodes: list[RangeHost] = []
    for extension in extensions:
        if not extension.get("enabled"):
            continue
        for machine in extension.get("machines") or []:
            nodes.append(
                new_range_host(machine, machine, machine, _EXT_ROLE, "extension", None)
            )
    return nodes


async def reseed(
    app: t.Any,
    session_id: str,
    capture_command: Capture | None = None,
) -> None:
    """Re-seed topology while preserving live state/layout for surviving nodes."""
    db = app.state.db
    session = await db.get_session(session_id)
    rng = await db.get_range(session_id)
    if session is None or rng is None:
        return
    snapshot = session.get("snapshot", {})
    # Resolved in the config's own tree, not the console's: `lab` is
    # repo-relative, so a config in another checkout has its ad/ over there.
    config = labconfig.session_lab_config_path(session, str(paths.repo_root()))
    seeded = labconfig.seed_topology(config, snapshot.get("provider"))
    existing_ids = {host["id"] for host in seeded["hosts"]}
    for node in await extension_nodes(session, capture_command):
        if node["id"] not in existing_ids:
            seeded["hosts"].append(node)
            existing_ids.add(node["id"])
    await db.upsert_range(session_id, labconfig.merge_reseed(rng, seeded))


async def repair_missing_config_hosts(
    app: t.Any, session_id: str, rng: t.Mapping[str, t.Any]
) -> PersistedRangeDocument:
    """Repair config hosts and metadata missing from an older topology.

    Returns the repaired range, or ``rng`` unchanged when there is nothing to do.

    A range is seeded once, inside create_session — which runs before the
    scaffold that generates the variant. An environment created through the
    console therefore comes up with infra nodes only, and stays that way:
    inventory_sync overlays cloud state onto hosts already present and never
    adds one, so a deployed host that was missing from the seed can never
    appear. That is not hypothetical — a range deployed with DC01 running showed
    an empty graph and three consecutive `hosts_updated: 0`.

    Reseeding on create fixes sessions made after that change. This exists for
    the ones already in that state, and for every other route to it: a variant
    generated by hand afterwards, a lab directory restored, a config whose tree
    was not reachable when the session was made.

    Deliberately a repair rather than an unconditional reseed. It fires only
    when the topology has NO config-sourced hosts or when an existing config
    host predates OS metadata. Both cases are self-limiting after one persisted
    repair. An unconditional reseed on every read would fight `/extensions`,
    whose nodes this seed does not produce.
    """
    document = t.cast(PersistedRangeDocument, rng)
    hosts = document.get("hosts") or []
    missing_config_hosts = not any(h.get("source") == "config" for h in hosts)
    missing_os_metadata = any(
        h.get("source") == "config" and "os" not in h for h in hosts
    )
    if not missing_config_hosts and not missing_os_metadata:
        return document

    db = app.state.db
    session = await db.get_session(session_id)
    if session is None:
        return document
    config = labconfig.session_lab_config_path(session, str(paths.repo_root()))
    if not config or not os.path.isfile(config):
        return document  # nothing to seed from yet; a greenfield range is legitimate

    seeded = labconfig.seed_topology(
        config, (session.get("snapshot") or {}).get("provider")
    )
    seeded_config_hosts = [
        h for h in seeded.get("hosts", []) if h.get("source") == "config"
    ]
    if not seeded_config_hosts:
        return document  # config parsed but defines no hosts — leave as-is

    if not missing_config_hosts:
        # Do not re-seed an established topology merely to backfill metadata:
        # that could change its node set and interfere with extension nodes.
        # Match by the stable config key first, with ID as a legacy fallback.
        seeded_by_key = {h.get("key"): h for h in seeded_config_hosts if h.get("key")}
        seeded_by_id = {h["id"]: h for h in seeded_config_hosts}
        repaired_hosts: list[RangeHost] = []
        changed = False
        for host in hosts:
            repaired_host = t.cast(RangeHost, dict(host))
            if host.get("source") == "config" and "os" not in host:
                host_key, host_id = host.get("key"), host.get("id")
                reference = (
                    seeded_by_key.get(host_key) if isinstance(host_key, str) else None
                ) or (seeded_by_id.get(host_id) if isinstance(host_id, str) else None)
                if reference is not None:
                    repaired_host["os"] = reference.get("os")
                    changed = True
            repaired_hosts.append(repaired_host)
        if not changed:
            return document
        repaired = t.cast(PersistedRangeDocument, dict(document))
        repaired["hosts"] = repaired_hosts
        await db.upsert_range(session_id, repaired)
        return repaired

    # Carry over anything the seed does not produce. merge_reseed makes the
    # seeded set authoritative and drops the rest, which is right for a genuine
    # re-seed but wrong here: this is a repair, and it must only ever ADD what
    # was missing. Extension nodes are the concrete case — `/extensions` on a
    # greenfield range leaves nodes that seed_topology knows nothing about, and
    # without this they and their saved positions vanish the moment the variant
    # shows up. reseed() solves the same problem by re-running
    # `extension list --json`; a subprocess inside a GET is not a trade worth
    # making, and preserving what is already there is strictly safer.
    seeded_ids = {h["id"] for h in seeded["hosts"]}
    for host in hosts:
        if host.get("id") not in seeded_ids:
            seeded["hosts"].append(host)
            seeded_ids.add(host.get("id"))

    repaired = t.cast(PersistedRangeDocument, labconfig.merge_reseed(document, seeded))
    await db.upsert_range(session_id, repaired)
    return repaired
