---
# https://clintboessen.blogspot.com/2010/04/group-scopes.html
# https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc755692(v=ws.10)
- name: Create Universal Groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: universal
    category: security
    path: "{{ item.value.path | default(omit) }}"
    state: present
  loop: "{{ ad_groups['universal'] | dict2items }}"
  loop_control:
    label: "Creating universal group: {{ item.key }}"
  when: ad_groups['universal'] is defined

- name: Create Global Groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: global
    category: security
    path: "{{ item.value.path | default(omit) }}"
    state: present
  loop: "{{ ad_groups['global'] | dict2items }}"
  loop_control:
    label: "Creating global group: {{ item.key }}"
  when: ad_groups['global'] is defined

- name: Create DomainLocal Groups
  microsoft.ad.group:
    name: "{{ item.key }}"
    scope: domainlocal
    category: security
    path: "{{ item.value.path | default(omit) }}"
    state: present
  loop: "{{ ad_groups['domainlocal'] | dict2items }}"
  loop_control:
    label: "Creating domainlocal group: {{ item.key }}"
  when: ad_groups['domainlocal'] is defined
